# -*- coding: utf-8 -*-
"""zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-unplEpGiE-Lpbrd3HxiLQWAg-r4Z4gO

# **ZOMATO DATA ANALYSIS PROJECT**

# STEP:1 pandas is used for data manipulation and analysis.
#        numpy is used for numerical operations.
#        matplotlib.pyplot and seaborn are used for data visualization.
"""

#importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# STEP:2 create the dataframe




"""

dataframe= pd.read_csv("Zomato data .csv")
print(dataframe)

dataframe

"""# STEP:3 cleaning the data"""

#for that converting the data type of the column rating
def handleRate(value):
  value=str(value).split('/')
  value=value[0]
  return float(value)

dataframe['rate']=dataframe['rate'].apply(handleRate)
print(dataframe.head())

"""STEP:4 check if there is any missing value or any null value, if therre comes like non-null i.e., that our data is good and we dont need to do any cleaning further"""

dataframe.info()

"""# QUESTION 1: What type of restaurant do the majority of customers order from?
# for that we will show it using graphs, using seaborn library
"""

dataframe.head()

#it shows only top 5 values of the graph

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel("Type of restaurent")

"""# Conclusin for Question 1: Majority of restaurents falls in din-in category.

# Question 2: How many votes has each type of restaurant received from customers?
"""

dataframe.head()

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})  # Corrected 'DataFrame'
plt.plot(result, c='blue', marker='o')
plt.xlabel("Type of restaurant", c="red", size=15)
plt.ylabel("Vote", c='red', size=15)

"""# Conclusion: Dining restaurents has recieved the maximum votes.

# Question 3: What are the ratings that the majority of restaurants have received?
"""

dataframe.head()

#histogram
plt.hist(dataframe['rate'],bins=5)
plt.title("Ratings Distribution")
plt.show()

"""# Conclusion: The majority of ratings given lies between 3.5 and 4.0 .

# Question 4: Zomato has observed that most couples order most of their food online. What is their average spending on each order?
"""

dataframe.head()

couple_data= dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data)

"""# Conclusion - The majority of couples preferr resturants with an approximate cost of 300 rupees

# Question 5: Which mode (online or offline) has received the maximum rating?
"""

dataframe.head()

plt.figure(figsize=(6,6))
sns.boxplot(x= "online_order", y="rate", data= dataframe)

"""# Conclusion: Offline order received lower rating in comparison to online order.

# Question 6: Which type of restaurant received more offline orders, so that Zomato can suggest customers with some good offers?
"""

dataframe.head()

pivot_table = dataframe.pivot_table (index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap="YlGnBu", fmt='d')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed in (Type)")
plt.show()

"""# Conclusion: Dining restaurants primarily accept offline orders, whereas cafes primarily receive online orders. This suggests that clients prefer orders in person at restaurants, but prefer online ordering at cafes."""